{% set name = "npe2" %}
{% set version = "0.7.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 55f66aaeff6c2c8d444222826f602799252e4a5008bed7f4e50290a314d712a7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - npe2 = npe2.cli:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - appdirs
    - python-build
    - psygnal >=0.3.0
    - pydantic
    - python >={{ python_min }}
    - tomli
    - tomli-w
    - pyyaml
    - rich
    - typer

test:
  imports:
    - npe2
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - npe2 --help

about:
  home: https://github.com/napari/npe2
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Second generation napari plugin engine
  doc_url: https://napari.org/
  dev_url: https://github.com/napari/npe2

extra:
  recipe-maintainers:
    - DragaDoncila
    - nclack
    - sofroniewn
    - jni
