{% set name = "npe2" %}
{% set version = "0.8.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 51afd432e5b0b2833d5e7506205f1d54411d5e00c5c94bf75c368c10bb7dd3eb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - npe2 = npe2.cli:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - platformdirs >=4.3.0
    - python-build
    - psygnal >=0.3.0
    - pydantic >=2.8
    - pydantic-extra-types >=2.8
    - python >={{ python_min }}
    - tomli >=2.0.2; python_version < "3.11"
    - tomli-w >=1.0
    - pyyaml >=6.0
    - rich >=14.0.0
    - typer >=0.15.4

test:
  imports:
    - npe2
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - npe2 --help

about:
  home: https://github.com/napari/npe2
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Second generation napari plugin engine
  doc_url: https://napari.org/
  dev_url: https://github.com/napari/npe2

extra:
  recipe-maintainers:
    - czaki
    - kevinyamauchi
    - kephale
    - DragaDoncila
    - jni
